- gatsby-browser.js
- package.json
- postcss.config.js
- src/styles/global.css
- tailwind.config.js
- yarn.lock
> init: Add Tailwind Config

- .github/workflows/lighthouse.yml
> feat(workflow): Setup Lighthouse Audit Action

- .github/workflows/lighthouse.yml
> feat(ci): Setup Lighthouse action

- .github/workflows/codeql-analysis.yml
> Create CodeQL Action

- .github/workflows/lighthouse.yml
> Adds LHCI Server Configs

- .github/workflows/lighthouse.yml
> Updates PR to PR Request for accessing secrets

- .github/workflows/lighthouse.yml
> Updates base ref and removes unwanted data

- src/components/shared/Typography/Body.jsx
- src/components/shared/Typography/Heading1.jsx
- src/components/shared/Typography/Heading2.jsx
- src/components/shared/Typography/Heading3.jsx
- src/components/shared/Typography/Heading4.jsx
- src/components/shared/Typography/HighlightBody.jsx
- tailwind.config.js
> fix: Update max-width in Tailwind Config & Add Breakpoints in Typography Elements

- src/components/TracksSection/Card.jsx
- src/components/TracksSection/Tracks.jsx
- src/components/TracksSection/Tracks.styles.jsx
- src/components/TracksSection/TracksData.jsx
- src/components/index.js
- src/pages/index.jsx
- tailwind.config.js
> feat: Add Hackathon Tracks Section

- src/components/TracksSection/Card.jsx
- src/components/TracksSection/styles.jsx
> fix: tracks

- config/website.js
- src/components/shared/SEO/SEO.jsx
- src/components/shared/SEO/structuredData.js
- src/pages/index.jsx
Added the structuredData.js file
❤️Thank you!
> feat: Added structuredData.js file

- config/content/FAQ.js
- config/content/Navigation.js
- config/content/index.js
- package.json
- src/components/FaqSection/Faq.jsx
- src/components/HeroSection/HeroContent.jsx
- src/components/HeroSection/HeroSection.jsx
- src/components/SponsorsSection/Sponsor.jsx
- src/components/TracksSection/Tracks.jsx
- src/components/marginals/Footer/Footer.jsx
- src/components/marginals/Navbar/DesktopNav.jsx
- src/components/marginals/Navbar/MobileNav.jsx
- src/components/shared/Button.jsx
- src/components/shared/Layout.jsx
- src/components/shared/SectionLayout.jsx
- src/pages/index.jsx
- src/utils/scrollTo.js
- yarn.lock
> feat: Add Scrolling In Navigation

- config/content/BeHacker.js
- config/content/FAQ.js
- config/content/Footer.js
- config/content/Hero.js
- config/content/Sponsors.js
- config/content/Tracks.js
- config/website.js
- src/components/FaqSection/Faq.jsx
- src/components/HeroSection/HeroContent.jsx
- src/components/marginals/Footer/Footer.jsx
> Add Content In The Website

- config/content/FAQ.js
- config/content/Footer.js
- config/content/Hero.js
- config/content/Tracks.js
- src/components/FaqSection/styles.jsx
- src/components/HackerSection/HackerCard.jsx
- src/components/HeroSection/HeroContent.jsx
- src/components/HeroSection/HeroSection.jsx
- src/components/TracksSection/Card.jsx
- src/components/TracksSection/styles.jsx
- src/components/marginals/Footer/Footer.jsx
> fix: Spacing, Content, Alignment Issues & Add Links In Footer

- src/pages/index.jsx
> feat: Add Hubspot Chat Embed

- config/content/Sponsors.js
- src/components/HeroSection/Ticker.jsx
- src/components/SponsorsSection/Sponsor.jsx
- src/components/SponsorsSection/styles.jsx
> feat: Update Sponsor Tiers | Add DO & Sawo

- config/content/BeHacker.js
- config/content/FAQ.js
- config/content/Footer.js
- config/content/Hero.js
- config/content/Navigation.js
- config/content/Sponsors.js
- config/content/Tracks.js
> fix: update cloudinary links with new account name

- config/content/FAQ.js
- config/website.js
- src/components/FaqSection/Faq.jsx
- src/components/FaqSection/styles.jsx
- src/components/HackerSection/HackerCard.jsx
- src/components/HeroSection/HeroContent.jsx
- src/components/shared/Modal.jsx
- src/components/shared/RegisterButton.jsx
- src/components/shared/index.js
- src/pages/playground.jsx
- src/utils/parseLinks.jsx
> feat: Add Terms and Conditions

- src/components/shared/RegisterButton.jsx
> Update Modal heading and body

- config/content/FAQ.js
- src/components/FaqSection/WhyWait.jsx
- src/components/FaqSection/styles.jsx
- src/components/SponsorsSection/styles.jsx
- src/components/marginals/Footer/styles.js
> feat: Update FAQ Illustration | Minor Style Fixes

- config/content/Sponsors.js
> feat: add sashido & filter_bean logo under beta sponsors

- config/content/Sponsors.js
> feat: add Filecoin under beta sponsors

- src/components/FaqSection/WhyWait.jsx
> fix: spelling error | WhyWait section

- config/content/Sponsors.js
> feat: add auth0 under beta sponsors

- config/content/Hero.js
- config/content/Moments.js
- config/content/Navigation.js
- config/content/Schedule.js
- config/content/index.js
- src/components/HeroSection/HeroContent.jsx
- src/components/HeroSection/Ticker.jsx
- src/components/Moments/Moments.jsx
- src/components/Schedule/Schedule.jsx
- src/components/index.js
- src/pages/index.jsx
- tailwind.config.js
> feat: moments section

- README.md
- live site url was not working so replaced it with working url
- href: https://dev.hacknitr.tech  ->  https://hacknitr.tech
> Fix live site url in readme.md

- CODE_OF_CONDUCT.md
- README.md
- config/content/About.js
- config/content/BeHacker.js
- config/content/Footer.js
- config/content/Hero.js
- config/content/Navigation.js
- config/content/Schedule.js
- config/content/Sponsors.js
- config/content/Stats.js
- config/content/index.js
- config/website.js
- src/components/AboutSection/About.jsx
- src/components/FaqSection/WhyWait.jsx
- src/components/HeroSection/HeroContent.jsx
- src/components/HeroSection/HeroSection.jsx
- src/components/Livestream/Interaction.jsx
- src/components/SponsorsSection/Sponsor.jsx
- src/components/Stats/Circle.jsx
- src/components/index.js
- src/components/marginals/Footer/Footer.jsx
- src/components/marginals/Navbar/DesktopNav.jsx
- src/components/marginals/Navbar/MobileNav.jsx
- src/pages/index.jsx
- src/styles/global.css
> Refactored the website

- src/components/HeroSection/HeroContent.jsx
> Added pre-register button

- gatsby-browser.js
- gatsby-config.js
- package.json
- postcss.config.js
- src/pages/index.js
- src/styles/global.css
- tailwind.config.js
- yarn.lock
This PR does the following task:
1. Installs tailwind css
2. Create global.css and Gatsby-brower.js 
3. Add necessary global css code
4. Makes sure tailwind is working
❤️Thank you!
> feat: install tailwind and config global css file

- src/components/shared/Typography/Body1.jsx
- src/components/shared/Typography/Body2.jsx
- src/components/shared/Typography/ButtonMeta.jsx
- src/components/shared/Typography/ButtonMetaLarge.jsx
- src/components/shared/Typography/Caption.jsx
- src/components/shared/Typography/Heading1.jsx
- src/components/shared/Typography/Heading2.jsx
- src/components/shared/Typography/Heading3.jsx
- src/components/shared/Typography/Heading4.jsx
- src/components/shared/Typography/NavText.jsx
- src/components/shared/index.js
- src/pages/index.js
- src/pages/playground.js
- src/styles/global.css
- tailwind.config.js
> feat: add typography

- src/components/shared/Container.jsx
- src/components/shared/SectionContainer.jsx
- src/components/shared/SectionLayout.jsx
- src/components/shared/Typography/Body1.jsx
- src/components/shared/Typography/Body2.jsx
- src/components/shared/Typography/ButtonMeta.jsx
- src/components/shared/Typography/ButtonMetaLarge.jsx
- src/components/shared/Typography/Caption.jsx
- src/components/shared/Typography/Heading1.jsx
- src/components/shared/Typography/Heading2.jsx
- src/components/shared/Typography/Heading3.jsx
- src/components/shared/Typography/Heading4.jsx
- src/components/shared/Typography/NavText.jsx
- src/components/shared/index.js
Added container, section container and section layout.
Fixed typography style issues 
❤️Thank you!
> Added Container, Section Container and Section Layout

- src/components/shared/DevfolioButton.jsx
Updated Slug Name for Devfolio button.
❤️Thank you!
> fix: updated slug name for Devfolio Button

- config/content/Footer.js
- config/content/Sponsors.js
- config/website.js
- src/components/HeroSection/HeroSection.jsx
- src/components/HeroSection/Ticker.jsx
- src/components/marginals/Footer/Footer.jsx
- src/components/shared/MLH.jsx
- src/pages/index.jsx
Added MLH banner
Added Ticker on hero section
Updated sponsor section
❤️Thank you!
> feat: added MLH banner, added footer links, added ticker & updated sponsors

- config/content/WhySponsor.js
- src/components/WhySponsorUs/WhySponsorUs.js
- src/components/WhySponsorUs/styles.jsx
- src/pages/index.js
- tailwind.config.js
> feat- Add WhySponsorUs section

- config/content/FAQ.js
- src/components/FaqSection/Faq.jsx
- src/components/FaqSection/styles.jsx
- src/components/shared/Typography/Caption.jsx
- src/pages/index.js
- src/utils/parseLinks.jsx
> feat: add FAQs Section

- src/components/carousel/Card.jsx
- src/components/carousel/Carousel.jsx
- src/components/carousel/CarouselMob.jsx
- src/components/carousel/ResponsiveCarousel.jsx
- src/pages/carouseltest.js
##Checklist
I created Carousel and CarouselMob components which gets rendered inside ResponsiveCarousel component based on screen size. 
I have also created a page named carouseltest to test the components in action.
It can be deleted later
> Added carousel after creating it

- config/content/About.js
- config/content/BeHacker.js
- config/content/FAQ.js
- config/website.js
- src/components/HeroSection/HeroContent.jsx
- src/components/HeroSection/JoinUs.jsx
- src/pages/index.jsx
> fix: updated old sections

- config/content/Sponsors.js
- src/components/SponsorsSection/Sponsor.jsx
> feat: add Sponsor

- config/content/Cards.js
- config/content/Footer.js
- config/content/WhySponsor.js
- src/components/FaqSection/Faq.jsx
- src/components/FaqSection/styles.jsx
- src/components/HeroSection/styles.jsx
- src/components/SponsorsSection/styles.jsx
- src/components/WhySponsorUs/WhySponsorUs.js
- src/components/WhySponsorUs/styles.jsx
- src/components/carousel/Card.jsx
- src/components/carousel/Carousel.jsx
- src/components/marginals/Footer/Footer.jsx
- src/components/marginals/Footer/styles.js
- src/components/marginals/NavBar/DesktopNav/style.jsx
- src/components/marginals/NavBar/MobileNav/style.jsx
- src/components/shared/MLHbanner.jsx
- src/components/shared/Typography/Body1.jsx
- src/components/shared/Typography/Body2.jsx
- src/components/shared/Typography/ButtonMeta.jsx
- src/components/shared/Typography/ButtonMetaLarge.jsx
- src/components/shared/Typography/Caption.jsx
- src/components/shared/Typography/Heading2.jsx
- src/components/shared/Typography/Heading3.jsx
- src/components/shared/Typography/Heading4.jsx
- src/components/shared/Typography/NavText.jsx
- src/pages/index.js
- src/styles/global.css
- tailwind.config.js
- yarn.lock
> Fix: styling issues

- config/content/Format.js
- src/components/Format/Modal.jsx
- src/components/Format/index.jsx
- src/components/Format/style.jsx
- src/components/shared/Button.jsx
- src/pages/index.js
- src/pages/playground.js
> feat: add format section

- config/content/Prizes.js
- config/content/Sponsors.js
- src/components/Prizes/Segments/DetailsBox.jsx
- src/components/Prizes/Segments/Navbar.jsx
- src/components/Prizes/Segments/Overall.jsx
- src/components/Prizes/Segments/PrizesForAll.jsx
- src/components/Prizes/Segments/Swags.jsx
- src/components/Prizes/Segments/Tracks.jsx
- src/components/Prizes/Styles.jsx
- src/components/Prizes/index.jsx
- src/pages/index.js
- src/pages/playground.js
> feat: add prizes section

- config/content/Cards.js
- src/components/carousel/Carousel.jsx
- yarn.lock
> chore : youtube links update

- config/content/Community.js
- config/index.js
- src/components/CommunitySection/Card.jsx
- src/components/CommunitySection/Carousel.jsx
- src/components/CommunitySection/CommunitySection.jsx
- src/components/CommunitySection/carousel.css
- src/components/index.js
- src/pages/index.js
> feat : community section added

- config/content/Prizes.js
- config/content/Schedule.js
> fix: workshop time

- config/content/Sponsors.js
- src/components/SponsorsSection/SponsorSection.jsx
> feat: add buidlerstribe logo

- config/content/FAQ.js
> chore : rulebook update

- config/content/About.js
- config/content/Community.js
- config/content/Hero.js
- config/content/Moments.js
- config/index.js
- config/navigation.js
- src/components/CommunitySection/CommunitySection.jsx
- src/components/Moments/index.jsx
- src/components/SponsorsSection/SponsorSection.jsx
- src/components/marginals/NavBar/DesktopNav/index.jsx
- src/components/marginals/NavBar/MobileNav/index.jsx
- src/pages/index.js
- yarn.lock
> feat: change data for initial setup of hacknitr 5.0

- gatsby-node.js
- redirects.json
> feat: add brochure

- tailwind.config.js
Reverts dscnitrourkela/project-oregano#235
> Revert "Feat/colortheme"

- src/styles/global.css
- tailwind.config.js
> Feat/colortheme 

- src/components/shared/Typography/Body1.jsx
- src/components/shared/Typography/Body2.jsx
- src/components/shared/Typography/Caption.jsx
- src/components/shared/Typography/Heading1.jsx
- src/components/shared/Typography/Heading2.jsx
- src/components/shared/Typography/Heading3.jsx
- src/components/shared/Typography/Heading4.jsx
- src/components/shared/Typography/NavText.jsx
- src/pages/playground.js
> fix: resolved issues

- .github/workflows/development.yml
- .github/workflows/eslint.yml
- .github/workflows/prettier.yml
- .husky/pre-commit
- package.json
- yarn.lock
> feat: setup husky and workflows

- src/components/timeline/Extensionboth.jsx
- src/components/timeline/styles.js
> fix:Width issue for Mobile S fixed

- config/content/Timelinecontent.js
- config/content/navbar.js
- package.json
- src/components/AboutUs/About.jsx
- src/components/AboutUs/styles.js
- src/components/Faq/Faq.jsx
- src/components/HeroSection/HeroBtn.jsx
- src/components/HeroSection/styles.jsx
- src/components/Prizes/Prizes.jsx
- src/components/Prizes/styles.js
- src/components/Sponsor/Sponsor.jsx
- src/components/TimelineSection/Timeline.jsx
- src/components/marginals/Footer/TermsNCredits.jsx
- src/components/marginals/Footer/styles.js
- src/components/marginals/Navbar/styles.js
- src/components/shared/Container.jsx
- src/components/shared/Particle.jsx
- src/pages/index.js
- src/pages/playground.js
- src/styles/carouselstyles.css
- src/styles/global.css
- yarn.lock
> chore: final setup

- config/content/FAQ.js
- config/navigation.js
- config/website.js
- src/components/shared/DevfolioBtn.jsx
> chore: prep for devfolio

- config/content/Faq.js
- src/components/Sponsor/Sponsor.jsx
> chore: minor update

- config/content/About.js
> chore: Update About.js

- config/content/About.js
- config/content/Faq.js
> chore: update faq

- config/content/Faq.js
- src/components/HeroSection/HeroSection.jsx
> chore: Update Faq.js

- src/components/HeroSection/HeroSection.jsx
- src/components/HeroSection/styles.jsx
> fix: button margin

- config/content/About.js
- config/content/Faq.js
> chore: update dates

- config/content/Hero.js
- src/components/HeroSection/HeroSection.jsx
- src/components/HeroSection/styles.jsx
- src/components/shared/Discord.jsx
- src/components/shared/DiscordMobile.jsx
- src/pages/playground.js
> feat:Discord btn

- config/content/Sponsor.js
- src/components/HeroSection/styles.jsx
- src/components/Sponsor/Sponsor.jsx
- src/components/Sponsor/styles.js
> Add alpha1 sponsors to Sponsor section

- config/content/Prizes.js
- src/pages/index.js
> chore: add prizes section

- config/content/Sponsor.js
> chore: Update replit logo

- config/content/Timelinecontent.js
- src/components/shared/DiscordMobile.jsx
updated dates for registration and acceptance periods.
❤️Thank you!
> fix: updated dates in timeline

- config/content/Sponsor.js
- src/components/Sponsor/Sponsor.jsx
- src/components/Sponsor/styles.js
> chore: update sponsors

- config/content/Sponsor.js
> chore: Update Sponsor.js
